//$file${.::../Inc::dpp.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::../Inc::dpp.hpp}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (C) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-QL-commercial
//
// The QP/C++ software is dual-licensed under the terms of the open-source
// GNU General Public License (GPL) or under the terms of one of the closed-
// source Quantum Leaps commercial licenses.
//
// Redistributions in source code must retain this top-level comment block.
// Plagiarizing this software to sidestep the license obligations is illegal.
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::../Inc::dpp.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef DPP_HPP_
#define DPP_HPP_

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Shared::DppSignals} ......................................................
enum DppSignals : QP::QSignal {
    TIMEOUT_DPP_SIG = QP::Q_USER_SIG, // posted by time event to Philo
    EAT_SIG,        // published by Table to let a Philo eat
    DONE_SIG,       // published by Philo when done eating
    PAUSE_SIG,      // published by BSP to pause the application
    SERVE_SIG,      // published by BSP to serve re-start serving forks
    TEST_SIG,       // published by BSP to test the application
    MAX_PUB_SIG,    // the last published signal

    HUNGRY_SIG,     // posted by hungry Philo to Table
    NEXT_SIG,       // ready for next event
    MAX_SIG         // the last signal
};

//${Shared::N_PHILO} .........................................................
constexpr std::uint8_t N_PHILO {5};

//${Shared::TableEvt} ........................................................
class TableEvt : public QP::QEvt {
public:
    std::uint8_t philoId;

public:
    void init(std::uint8_t id) {
        philoId = id;
    }
}; // class TableEvt

//${Shared::AO_Philo[N_PHILO]} ...............................................
extern QP::QActive * const AO_Philo[N_PHILO];

//${Shared::AO_Table} ........................................................
extern QP::QActive * const AO_Table;

//${Shared::AO_TerminalDpp} ..................................................
extern QP::QActive * const AO_TerminalDpp;

} // namespace APP
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // DPP_HPP_
